### ISSUE TITLE
Error in advancedMatchingList when importing container while no values set

### ISSUE THREAD

**Issue by rrmn** [gtm-templates-simo-ahava/facebook-pixel#12]
Cheers Simo,

there's a small hiccup when you try to import a pixel tag that has **advanced matching turned on**, but an **empty matching list**. 

## Steps to reproduce:

1. Turn advanced matching on for any FB Pixel tag, but leave matching parameters/values empty
1. Export container
1. Import exported container into workspace

## Result:
<img width="943" alt="Screenshot 2020-08-06 at 23 37 53" src="https://user-images.githubusercontent.com/14080347/89586813-a79fdd80-d840-11ea-8cdd-8b71654374fd.png">

**Comment by sahava** [comment]
This is a bug with GTM itself and a regression of sorts if you've updated the template to the version where AdvancedMatchingList can't be left empty.

The latest version of the pixel template doesn't let you save the tag if you've checked Advanced Matching but haven't added a single parameter.
