### ISSUE TITLE
Help on adding userId / external_id

### ISSUE THREAD

**Issue by jimbalatero** [gtm-templates-simo-ahava/facebook-pixel#16]
Since user properties was [deprecated](https://developers.facebook.com/docs/analytics/send_data/user_properties/), how do we input the `userId`?

And as I checked the code, Object Properties is not the right section to add `userId`.

Maybe `advancedMatchingList` need to have the `external_id` dropdown? https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters

Thank you.

**Comment by sahava** [comment]
Thanks for the feedback.

Yes, `external_id` replaces it. I have updated the template to include External Id in advanced matching - it should be updated in the gallery shortly.

6eab67135d4e8b6052332e9b52dcb3d7e88b5b2c
