### ISSUE TITLE
Adding an eventID parameter and value to the existing Facebook Gallery Tag

### ISSUE THREAD

**Issue by taavikalvi** [gtm-templates-simo-ahava/facebook-pixel#18]
This eventID should help us to prevent duplicate transactions issue regarding Facebook. Here's the official documentation: https://developers.facebook.com/docs/marketing-api/conversions-api/deduplicate-pixel-and-server-events/ 

I attached the screenshot of the Custom HTML tag that uses the eventID parameter:

![event ID](https://user-images.githubusercontent.com/24587698/98798378-7ffb7b00-2416-11eb-80a2-2782d405ff8a.png)

**Comment by sahava** [comment]
Fixed in 11c004614f6b8f7cc999caabef521086116ce302
