### ISSUE TITLE
Enhanced ecommerce

### ISSUE THREAD

**Issue by shamoonak** [gtm-templates-simo-ahava/facebook-pixel#3]
Is there a way I can get the variables into the facebook pixel so that I can use dynamic retargeting and other features of facebook ads?

**Comment by shamoonak** [comment]
I have a client who is running an online store in opencart. They are using the default facebook extension with 1 pixel. I need to install a second pixel so I am using Google Tag Manager. I am unable to get the variables to be passed to the facebook pixel.

**Comment by sahava** [comment]
Enhanced Ecommerce added in ef005f12f5429183534e74e117365e02dac51cd0
