### ISSUE TITLE
After newest update today FB pixel is not working at all. Code seems to work in GTM, however FB is not registering the pixel. 

### ISSUE THREAD

**Issue by SarahG321** [gtm-templates-simo-ahava/facebook-pixel#4]

**Comment by sahava** [comment]
Hi,

I can't reproduce this - it's worked fine when I've tested it. Is this still a problem? If it is, could you share the Preview mode link to your container as well as a URL where the issue persist? Thanks!

**Comment by SarahG321** [comment]
Sorry I missed this email. I changed the container to a previous version
and then it worked again. I haven't dared to update to the newest version
yet. I'll test it and if the problem persists I'll let you know. Thanks for
replying to me.

Best,

Sarah
