### ISSUE TITLE
Customer Info Data Parameters - not populating

### ISSUE THREAD

**Issue by jpool-cf** [gtm-templates-simo-ahava/facebook-pixel#5]
First off, this template is awesome, thank you for putting this together!

I'm having trouble getting any of the Customer Information Data Parameters to populate during a Purchase event, regardless of what I point them to as a Parameter value.

Example: I pointed Email to one of GTM's Built-In Variables, and it still won't populate. Initially I was using a dataLayer variable (that I could see populating in the preview pane).

The only thing I haven't tried yet is hardcoding a value into one of the customer parameters to see if that works.

Any known issues around this? Thanks!

**Comment by sahava** [comment]
Hm, very strange. I just tested and it works fine. The user data is hashed and passed as the `&ud[param_key]` parameter. So City would be `&ud[ct]` for example.

Could you check again? If it still doesn't work, could you share a container export with me and I'll take a look at what's wrong.

**Comment by sahava** [comment]
Closed for now since no reply.
