### ISSUE TITLE
GTM preview says `Exception thrown` when tag fires

### ISSUE THREAD

**Issue by stephanschubert** [gtm-templates-simo-ahava/facebook-pixel#9]
Hi, I used your great template a while ago in another website and it worked fine.

But sth is off now... Would this [shared preview link](https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-WDTB5WG&check_preview_status=1&gtm_auth=lv9TeR-Ma04g5S1QTVEDvQ&gtm_preview=env-13&gtm_debug=x&url=https%3A%2F%2Fd34vhhr1t6sulw.cloudfront.net%2F) help debugging this?

The tag's setup is pretty standard:

![image](https://user-images.githubusercontent.com/3699/86541903-30112280-bf11-11ea-8803-70ba7aeb0d4e.png)

**Comment by sahava** [comment]
Hi,

This is becasue you have "Advanced Matching" checked but haven't added any customer info parameters. A quick fix is to remove the checkbox.

I'll update the template to not fail if the parameters are not populated.

**Comment by stephanschubert** [comment]
@sahava Ah, you're right. It works now. Thanks for the quick help!
